"""add mailbox poll status fields

Revision ID: 10d4226733ce
Revises: 30326c54a8aa
Create Date: 2026-08-27 11:26:25.072397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10d4226733ce'
down_revision: Union[str, None] = '30326c54a8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailboxes', sa.Column('last_poll_status', sa.Enum('OK', 'ERROR', name='mailboxpollstatus', native_enum=False), nullable=True))
    op.add_column('mailboxes', sa.Column('last_poll_error_message', sa.Text(), nullable=True))
    op.add_column('mailboxes', sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True))
    # NOTE: autogenerate also proposed dropping products.ix_products_search_document
    # here - a functional GIN index (see a1b2c3d4e5f6) that isn't represented in
    # SQLAlchemy metadata, so autogenerate always misreads it as "removed".
    # Unrelated to this migration; left in place deliberately (see also
    # 30326c54a8aa, which hit the same false positive).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailboxes', 'last_poll_at')
    op.drop_column('mailboxes', 'last_poll_error_message')
    op.drop_column('mailboxes', 'last_poll_status')
    # ### end Alembic commands ###
