"""add product suggestions table

Revision ID: 30326c54a8aa
Revises: a1b2c3d4e5f6
Create Date: 2026-08-26 11:52:18.630252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30326c54a8aa'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_suggestions',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('VORGESCHLAGEN', 'FREIGEGEBEN', 'ABGELEHNT', name='productsuggestionstatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_product_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_suggestions_email_message_id'), 'product_suggestions', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_product_suggestions_sku'), 'product_suggestions', ['sku'], unique=False)
    op.create_index(op.f('ix_product_suggestions_status'), 'product_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_product_suggestions_tenant_id'), 'product_suggestions', ['tenant_id'], unique=False)
    # NOTE: autogenerate also proposed dropping products.ix_products_search_document
    # here - a functional GIN index (see a1b2c3d4e5f6) that isn't represented in
    # SQLAlchemy metadata, so autogenerate always misreads it as "removed".
    # Unrelated to this migration; left in place deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_suggestions_tenant_id'), table_name='product_suggestions')
    op.drop_index(op.f('ix_product_suggestions_status'), table_name='product_suggestions')
    op.drop_index(op.f('ix_product_suggestions_sku'), table_name='product_suggestions')
    op.drop_index(op.f('ix_product_suggestions_email_message_id'), table_name='product_suggestions')
    op.drop_table('product_suggestions')
    # ### end Alembic commands ###
