"""add rfc822 message id to email_messages

Revision ID: 5867639a531e
Revises: c3173be18d58
Create Date: 2026-08-16 16:01:32.791627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5867639a531e'
down_revision: Union[str, None] = 'c3173be18d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('rfc822_message_id', sa.String(length=998), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'rfc822_message_id')
    # ### end Alembic commands ###
