"""add product embedding column

Revision ID: 73555194c2a8
Revises: 10d4226733ce
Create Date: 2026-08-27 11:50:21.970808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '73555194c2a8'
down_revision: Union[str, None] = '10d4226733ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # NOTE: autogenerate also proposed dropping products.ix_products_search_document
    # here - a functional GIN index (see a1b2c3d4e5f6) that isn't represented in
    # SQLAlchemy metadata, so autogenerate always misreads it as "removed".
    # Unrelated to this migration; left in place deliberately (see also
    # 30326c54a8aa and 10d4226733ce, which hit the same false positive).
    op.create_index('ix_products_embedding_hnsw', 'products', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_embedding_hnsw', table_name='products', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('products', 'embedding')
    # ### end Alembic commands ###
