"""add case deal stage

Revision ID: 9b496bb99ea5
Revises: 73555194c2a8
Create Date: 2026-09-09 06:32:16.266945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b496bb99ea5'
down_revision: Union[str, None] = '73555194c2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (autogenerate didn't propose one): a
    # NOT NULL column on an existing, possibly non-empty table needs a
    # backfill value for its current rows. ANFRAGE also happens to be the
    # model's own Python-side default for a brand new Case.
    op.add_column('cases', sa.Column('deal_stage', sa.Enum('ANFRAGE', 'ANGEBOT_ERSTELLT', 'NACHFASSEN', 'GEWONNEN', 'VERLOREN', name='dealstage', native_enum=False), nullable=False, server_default='ANFRAGE'))
    op.add_column('cases', sa.Column('deal_stage_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # NOTE: autogenerate also proposed dropping products.ix_products_search_document
    # here - a functional GIN index (see a1b2c3d4e5f6) that isn't represented in
    # SQLAlchemy metadata, so autogenerate always misreads it as "removed".
    # Unrelated to this migration; left in place deliberately (see also
    # 30326c54a8aa, 10d4226733ce and 73555194c2a8, which hit the same false
    # positive).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'deal_stage_changed_at')
    op.drop_column('cases', 'deal_stage')
    # ### end Alembic commands ###
