/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/gmail/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gmail Connect */
        get: operations["gmail_connect_api_auth_gmail_connect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/gmail/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gmail Callback */
        get: operations["gmail_callback_api_auth_gmail_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mailboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mailboxes */
        get: operations["list_mailboxes_api_mailboxes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mailboxes/{mailbox_id}/poll-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll Now
         * @description Manual trigger for local testing, so a developer doesn't have to
         *     wait for the next scheduler tick to see a test mail come through.
         */
        post: operations["poll_now_api_mailboxes__mailbox_id__poll_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mailboxes/{mailbox_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Mailbox
         * @description Removes a connected mailbox.
         *
         *     Previously only possible via direct SQL. Mail, drafts, attachments and
         *     product suggestions cascade at the database level; contacts/cases left
         *     referencing zero remaining mail are cleaned up alongside them - see
         *     app/services/mailbox_cleanup.py for why that can't be a plain CASCADE.
         */
        delete: operations["delete_mailbox_api_mailboxes__mailbox_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["list_drafts_api_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_drafts__draft_id__get"];
        /** Update Draft */
        put: operations["update_draft_api_drafts__draft_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Draft
         * @description Sends an approved draft, exactly once.
         *
         *     Two phases, because sending is irreversible:
         *
         *     1. Claim. The draft row is locked, checked, moved to FREIGEGEBEN and
         *        committed. The lock is released immediately; the claim is durable.
         *        A second, concurrent approval now blocks on the lock, then sees a
         *        status that is no longer ENTWURF and is rejected - where previously
         *        both requests passed the check and the customer got the mail twice.
         *     2. Send, then record. Only after Gmail accepts does the draft move to
         *        VERSENDET and the mail to ERLEDIGT.
         *
         *     If the process dies between the two phases the draft stays in
         *     FREIGEGEBEN, visible and recoverable by a human. That is the
         *     deliberate direction of the trade: a stuck draft can be fixed, a
         *     duplicate mail to a customer cannot be un-sent.
         */
        post: operations["approve_draft_api_drafts__draft_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Draft */
        post: operations["reject_draft_api_drafts__draft_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Emails */
        get: operations["list_emails_api_emails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emails/{email_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Email */
        get: operations["get_email_api_emails__email_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts_api_contacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["get_contact_api_contacts__contact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Knowledge */
        get: operations["search_knowledge_api_knowledge_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_knowledge_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_knowledge_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/products/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Products */
        post: operations["import_products_api_knowledge_products_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Product */
        put: operations["update_product_api_knowledge_products__product_id__put"];
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_knowledge_products__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Suggestions */
        get: operations["list_product_suggestions_api_product_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-suggestions/{suggestion_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Product Suggestion
         * @description Creates the real catalog Product from a pending suggestion.
         *
         *     Unlike Draft approval there is no external side effect to protect (no
         *     mail gets sent) - the row lock only has to stop two concurrent
         *     approvals from both creating a Product for the same suggestion.
         */
        post: operations["approve_product_suggestion_api_product_suggestions__suggestion_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-suggestions/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Product Suggestion */
        post: operations["reject_product_suggestion_api_product_suggestions__suggestion_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_products_api_knowledge_products_import_post */
        Body_import_products_api_knowledge_products_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CaseDetailOut */
        CaseDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            status: components["schemas"]["CaseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Contacts */
            contacts: components["schemas"]["ContactOut"][];
            /** Email Count */
            email_count: number;
            /** Emails */
            emails: components["schemas"]["EmailOut"][];
        };
        /** CaseListItemOut */
        CaseListItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            status: components["schemas"]["CaseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Contacts */
            contacts: components["schemas"]["ContactOut"][];
            /** Email Count */
            email_count: number;
        };
        /** CaseOut */
        CaseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            status: components["schemas"]["CaseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "offen" | "geschlossen";
        /** ContactDetailOut */
        ContactDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Email Address */
            email_address: string;
            /** Company */
            company: string | null;
            /** Total Inquiries */
            total_inquiries: number;
            last_status: components["schemas"]["ContactLastStatus"] | null;
            /** Last Contact At */
            last_contact_at: string | null;
            /** Needs Followup */
            needs_followup: boolean;
            /** Emails */
            emails: components["schemas"]["EmailSummaryOut"][];
        };
        /**
         * ContactLastStatus
         * @description The three-value status a contact overview needs - derived at
         *     request time, never persisted (see routes/contacts.py:_last_status).
         *
         *     It combines two things that are stored separately: EmailStatus (was the
         *     latest inquiry answered?) and CaseStatus (was its case closed?).
         * @enum {string}
         */
        ContactLastStatus: "offen" | "beantwortet" | "abgeschlossen";
        /** ContactListItemOut */
        ContactListItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Email Address */
            email_address: string;
            /** Company */
            company: string | null;
            /** Total Inquiries */
            total_inquiries: number;
            last_status: components["schemas"]["ContactLastStatus"] | null;
            /** Last Contact At */
            last_contact_at: string | null;
            /** Needs Followup */
            needs_followup: boolean;
        };
        /** ContactOut */
        ContactOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email Address */
            email_address: string;
            /** Name */
            name: string | null;
            /** Company */
            company: string | null;
        };
        /** DraftOut */
        DraftOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email Message Id
             * Format: uuid
             */
            email_message_id: string;
            /** Subject */
            subject: string | null;
            /** Body */
            body: string;
            status: components["schemas"]["DraftStatus"];
            /** Rag Context Summary */
            rag_context_summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Sent At */
            sent_at: string | null;
            email_message: components["schemas"]["EmailSummaryOut"];
        };
        /** DraftRejectIn */
        DraftRejectIn: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * DraftStatus
         * @enum {string}
         */
        DraftStatus: "entwurf" | "freigegeben" | "abgelehnt" | "versendet";
        /** DraftUpdateIn */
        DraftUpdateIn: {
            /** Subject */
            subject?: string | null;
            /** Body */
            body: string;
        };
        /** EmailOut */
        EmailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject */
            subject: string | null;
            /** Sender Address */
            sender_address: string;
            /** Sender Name */
            sender_name: string | null;
            /** Snippet */
            snippet: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            wichtigkeits_kategorie: components["schemas"]["WichtigkeitsKategorie"] | null;
            typ: components["schemas"]["TypKategorie"];
            status: components["schemas"]["EmailStatus"];
            contact: components["schemas"]["ContactOut"] | null;
            case: components["schemas"]["CaseOut"] | null;
            /** Raw Content */
            raw_content: string;
            /** Classification Confidence */
            classification_confidence: number | null;
            /** Classification Reasoning */
            classification_reasoning: string | null;
        };
        /**
         * EmailStatus
         * @enum {string}
         */
        EmailStatus: "neu" | "abgelegt" | "wartet_auf_freigabe" | "erledigt" | "ausgeblendet";
        /**
         * EmailSummaryOut
         * @description Everything a list view needs - deliberately without `raw_content`,
         *     which is the largest field by far and never rendered in a list.
         */
        EmailSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject */
            subject: string | null;
            /** Sender Address */
            sender_address: string;
            /** Sender Name */
            sender_name: string | null;
            /** Snippet */
            snippet: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            wichtigkeits_kategorie: components["schemas"]["WichtigkeitsKategorie"] | null;
            typ: components["schemas"]["TypKategorie"];
            status: components["schemas"]["EmailStatus"];
            contact: components["schemas"]["ContactOut"] | null;
            case: components["schemas"]["CaseOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MailboxOut */
        MailboxOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email Address */
            email_address: string;
            /** Is Active */
            is_active: boolean;
            /** Last Synced At */
            last_synced_at: string | null;
            last_poll_status: components["schemas"]["MailboxPollStatus"] | null;
            /** Last Poll Error Message */
            last_poll_error_message: string | null;
            /** Last Poll At */
            last_poll_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MailboxPollStatus
         * @description Outcome of the mailbox's most recent poll *attempt* - see
         *     app/workers/tasks.py. Distinct from per-message failures (see
         *     ActionLog "mail_processing_failed"): one bad mail costs that mail, not
         *     the mailbox, so it does not flip this to ERROR. This reflects whether
         *     the poll job itself completed - previously visible only in container
         *     logs.
         * @enum {string}
         */
        MailboxPollStatus: "ok" | "error";
        /**
         * PollTriggerOut
         * @description Result of a manual poll trigger.
         *
         *     `job_id` is null when a poll for this mailbox was already in flight -
         *     see app/workers/queue.py for why a second one is not stacked.
         */
        PollTriggerOut: {
            /** Job Id */
            job_id: string | null;
            /** Status */
            status: string;
        };
        /** ProductCreateIn */
        ProductCreateIn: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Sku */
            sku?: string | null;
            /** Price */
            price?: number | string | null;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Availability */
            availability?: string | null;
            /** Specs */
            specs?: {
                [key: string]: unknown;
            };
        };
        /** ProductImportResult */
        ProductImportResult: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: string[];
        };
        /** ProductOut */
        ProductOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Category */
            category: string | null;
            /** Sku */
            sku: string | null;
            /** Price */
            price: string | null;
            /** Currency */
            currency: string;
            /** Availability */
            availability: string | null;
            /** Specs */
            specs: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProductSuggestionOut */
        ProductSuggestionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email Message Id
             * Format: uuid
             */
            email_message_id: string;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            status: components["schemas"]["ProductSuggestionStatus"];
            /** Created Product Id */
            created_product_id: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Rejected Reason */
            rejected_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            email_message: components["schemas"]["EmailSummaryOut"];
        };
        /** ProductSuggestionRejectIn */
        ProductSuggestionRejectIn: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * ProductSuggestionStatus
         * @enum {string}
         */
        ProductSuggestionStatus: "vorgeschlagen" | "freigegeben" | "abgelehnt";
        /**
         * ProductUpdateIn
         * @description All fields optional - PUT applies a partial update (only supplied
         *     fields are changed), which is friendlier for an edit form that only
         *     resends what the user touched.
         */
        ProductUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Sku */
            sku?: string | null;
            /** Price */
            price?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Availability */
            availability?: string | null;
            /** Specs */
            specs?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TypKategorie
         * @enum {string}
         */
        TypKategorie: "bestellung" | "anfrage" | "keiner";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WichtigkeitsKategorie
         * @enum {string}
         */
        WichtigkeitsKategorie: "antwort_erforderlich" | "information" | "newsletter" | "spam_verdacht";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    gmail_connect_api_auth_gmail_connect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    gmail_callback_api_auth_gmail_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_mailboxes_api_mailboxes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxOut"][];
                };
            };
        };
    };
    poll_now_api_mailboxes__mailbox_id__poll_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollTriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_mailbox_api_mailboxes__mailbox_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_drafts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["DraftStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_draft_api_drafts__draft_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_draft_api_drafts__draft_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_draft_api_drafts__draft_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_emails_api_emails_get: {
        parameters: {
            query?: {
                wichtigkeit?: components["schemas"]["WichtigkeitsKategorie"] | null;
                typ?: components["schemas"]["TypKategorie"] | null;
                status?: components["schemas"]["EmailStatus"] | null;
                include_spam?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_email_api_emails__email_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListItemOut"][];
                };
            };
        };
    };
    get_case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts_api_contacts_get: {
        parameters: {
            query?: {
                /** @description Overrides the follow-up threshold (days) for this request only. Defaults to the configured contact_followup_threshold_days setting. */
                followup_days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact_api_contacts__contact_id__get: {
        parameters: {
            query?: {
                followup_days?: number | null;
            };
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_api_knowledge_search_get: {
        parameters: {
            query?: {
                q?: string | null;
                contact_id?: string | null;
                case_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_knowledge_products_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_knowledge_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_products_api_knowledge_products_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_products_api_knowledge_products_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_knowledge_products__product_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_knowledge_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_suggestions_api_product_suggestions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProductSuggestionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSuggestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_product_suggestion_api_product_suggestions__suggestion_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSuggestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_product_suggestion_api_product_suggestions__suggestion_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductSuggestionRejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSuggestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
